name: teacher_mobile
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8
  
  # File handling and CSV operations
  file_picker: ^8.0.0+1
  csv: ^6.0.0
  path_provider: ^2.1.2
  
  # Notifications
  flutter_local_notifications: ^17.2.3
  permission_handler: ^11.3.1
  timezone: ^0.9.4
  qr_flutter: ^4.1.0

  # Networking
  http: ^1.2.1
  
  # Charts
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - web/icons/Icon-512.png
    - lib/assets/aclc logo.png
