name: teacher_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.3
  jwt_decoder: ^2.0.1
  intl: ^0.18.1
  table_calendar: ^3.0.9
  qr_flutter: ^4.1.0
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
     - lib/images/aclc_logo.png

